# Generated by Django 3.0.1 on 2019-12-26 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
        ('date', '0002_auto_20191223_1804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='date',
            name='father',
        ),
        migrations.AlterField(
            model_name='date',
            name='child',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.Student'),
        ),
    ]
