# Generated by Django 3.0.1 on 2019-12-24 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Homepage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(blank=True, default=' ', max_length=100, null=True)),
                ('Planning', models.ImageField(blank=True, null=True, upload_to='planning/')),
                ('planning_cantine', models.ImageField(blank=True, null=True, upload_to='planning/')),
                ('planning_goute', models.ImageField(blank=True, null=True, upload_to='planning/')),
                ('citation', models.ImageField(blank=True, null=True, upload_to='planning/')),
                ('message', models.TextField(blank=True, default=' ', null=True)),
                ('daily_img', models.ImageField(blank=True, null=True, upload_to='daily-img/')),
                ('group', models.CharField(choices=[('petite-section', 'Petite-Section'), ('moyenne-section', 'Moyenne-Section'), ('Creche', 'Creche')], max_length=250)),
                ('Event_title', models.CharField(blank=True, default=' ', max_length=100, null=True)),
                ('Event_description', models.TextField(blank=True, default=' ', null=True)),
                ('Event_date', models.DateField(blank=True, null=True)),
                ('Event_img', models.ImageField(blank=True, null=True, upload_to='events/')),
            ],
        ),
    ]
