# Generated by Django 3.0.1 on 2019-12-24 03:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_first_name', models.CharField(max_length=20)),
                ('student_last_name', models.CharField(max_length=20)),
                ('student_sexe', models.CharField(max_length=25)),
                ('nationality', models.CharField(max_length=20)),
                ('student_birthday', models.CharField(max_length=20)),
                ('father_name', models.CharField(max_length=25)),
                ('father_profession', models.CharField(max_length=25)),
                ('father_phone_number', models.CharField(max_length=25)),
                ('mother_name', models.CharField(max_length=20)),
                ('mother_profession', models.CharField(max_length=25)),
                ('mother_phone_number', models.CharField(max_length=25)),
                ('complete_adress', models.CharField(max_length=100)),
                ('tlf_fix_number', models.CharField(max_length=30)),
                ('img', models.ImageField(blank=True, default='images/profile-2398782_960_720_ZjcWbXL.png', null=True, upload_to='')),
                ('photo_1', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('photo_2', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('photo_3', models.ImageField(blank=True, null=True, upload_to='iamges/')),
                ('photo_4', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('photo_5', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('photo_6', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('section', models.CharField(choices=[('petite-section', 'Petite-Section'), ('moyenne-section', 'Moyenne-Section'), ('Creche', 'Creche')], max_length=25)),
                ('nom_du_pediatre', models.CharField(blank=True, max_length=25, null=True)),
                ('tlf_pediatre', models.CharField(blank=True, max_length=25, null=True)),
                ('other_responsible_name', models.CharField(blank=True, max_length=25, null=True)),
                ('other_responsible_tlf', models.CharField(blank=True, max_length=25, null=True)),
                ('is_alergetic', models.CharField(max_length=25)),
                ('auto_medic_buy', models.CharField(max_length=25)),
                ('study_forfait', models.CharField(choices=[('temps complet', 'Temp Complet'), ('temps partiel', 'Temps Partiel')], max_length=25)),
                ('parent', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
